GET http://localhost:3000/lists

###
GET http://localhost:3000/lists/2

###
POST http://localhost:3000/lists
Content-Type: application/json

{
  "name": "TesteAgora"
}

###
GET http://localhost:3001/lists

###
POST http://localhost:3001/lists
Content-Type: application/json

{
  "id": 5000,
  "name": "Vai?"
}